.pragma library

var HEADER_HEIGHT = 70;
var HEADER_COLOR = '#1080DD';
var FONT_SIZE_LARGE = 32;
var NORMAL_MARGIN = 20;
var SMALL_MARGIN = 10;
var FONT_DEFAULT_SIZE = 24;
var FONT_FAMILY = "Nokia Pure Text";
var COLOR_FOREGROUND = "#191919";
var COLOR_INVERTED_FOREGROUND = "#ffffff";

var DEFAULT_TEXT_FILD_WIDTH = 250;
var DEFAULT_TEXT_FILD_HEIGHT = 52;

var LIST_SUBTITLE_COLOR = "#505050";
var LIST_SUBTITLE_COLOR_INVERTED = "#d2d2d2";

var IMAP_FLAGS = '(\\Seen)';
